const mockAPNData = [
    {
        "stateName": "California",
        "acreage": 0.22231112,
        "assessorIdentificationNumber": 2004001003,
        "zip": 91304,
        "streetName": "FAUST AVE",
        "city": "LOS ANGELES",
        "zoningCode": "LARE9",
        "yearBuilt": 1973,
        "countyName": "Los Angeles",
        "buildingSqft": 3007.1873,
        "unbuiltSf": 6676.6855,
        "healthcare1Mile": 27,
        "opportunityLevel": "High Resource",
        "highQualityTransitArea": false,
        "absoluteConstraint": false,
        "variableConstraint": false,
        "environmentJusticeArea": false,
        "landUseClassName": "Single Family Residential",
        "fireHazard": false,
        "searise1Meter": false,
        "searise2Meter": false,
        "floodPlainZone": false,
        "equakeZone": false,
        "liquafactionZone": true,
        "landslideZone": false,
        "protectedArea": false,
        "wildlifeArea": false,
        "cnddbRareSpeciesArea": false,
        "landCurrentValue": 711689,
        "situsHouseNo": 8321,
        "firstOwnerName": "PATEL HANISH B AND ALPA P",
        "lastSaleAmount": 9,
        "legalFirstLine": "TRACT NO 25040   LOT   99",
        "trustNames": "PATEL TRUST",
        "lastSaleDateYear": 2005,
        "lastSaleDateMonth": 9,
        "lastSaleDateDay": 6,
        "impairmentDescription": "None",
        "taxStatus": "Taxes paid not delinquent"
    }
]

export default mockAPNData